apiVersion: apps/v1
kind: Deployment
metadata:
  name: cv-site
  namespace: cv-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cv-site
  template:
    metadata:
      labels:
        app: cv-site
    spec:
      containers:
        - name: cv-site
          image: ghcr.io/jakechowdhury/cv-site:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /
              port: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80